name: CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t ${{ github.event.repository.name }} .
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      CONTAINER_NAME: devops-web-container

  run_container:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Docker container
        run: |
          docker run -d -p 8085:80 --name $CONTAINER_NAME $IMAGE_NAME
          docker exec $CONTAINER_NAME robot tests.robot
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      CONTAINER_NAME: devops-web-container
